python mailer
Gator-Bytes-Foundation/p4hApp pull request #132
Opened 2023-05-31 21:24 UTC by kphlex

2023-05-31 21:44 UTC, lcundiff requested changes

2023-05-31 21:44 UTC, lcundiff commented on secrets_dev.yml
> +gmail_pwd: hYuMo258hq!/
Do you want this email and password pushed to secrets dev? Just making sure.

2023-05-31 21:44 UTC, lcundiff commented on Pipfile
> +[[source]]
What does this file do? It looks like requirements.txt since it shows all the packages.

2023-05-31 21:44 UTC, lcundiff commented on src/mailer/alerts.py
> +sys.path.append(p4hApp_dir)
```suggestion
p4hApp_dir = os.path.abspath(os.path.join(current_dir, "../../"))
sys.path.append(p4hApp_dir)
```
Would something like this be possible?

2023-06-05 21:50 UTC, mrbrown444 reviewed
Pls can I use this project as a webmail smtp ,to send mails in bulk ... ?thanks

2023-06-22 00:04 UTC, lcundiff approved these changes

2023-06-22 00:04 UTC, merged