Initial Design
Gator-Bytes-Foundation/p4hApp pull request #136
Opened 2023-07-01 23:31 UTC by moneshvenkul

2023-07-06 00:12 UTC, lcundiff requested changes

2023-08-29 19:37 UTC, lcundiff commented on src/static/client/app/components/reset-password/reset-password.component.scss
> +    border-radius: 4px;
@moneshvenkul

2023-08-30 23:29 UTC, moneshvenkul commented on src/static/client/app/components/reset-password/reset-password.component.scss
> +    border-radius: 4px;
Yes created a common scss and removed the dulpications

2023-08-30 23:55 UTC, lcundiff approved these changes

2023-08-30 23:55 UTC, merged